/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: GPSData.idl
  Source: GPSData.cpp
  Cyclone DDS: v0.10.5

*****************************************************************/
#include "GPSData.hpp"

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::platform::sensors::GPSData>() {
  static thread_local std::mutex mtx;
  static thread_local propvec props;
  static thread_local entity_properties_t *props_end = nullptr;
  static thread_local std::atomic_bool initialized {false};
  key_endpoint keylist;
  if (initialized.load(std::memory_order_relaxed)) {
    auto ptr = props.data();
    while (ptr < props_end)
      (ptr++)->is_present = false;
    return props;
  }
  std::lock_guard<std::mutex> lock(mtx);
  if (initialized.load(std::memory_order_relaxed)) {
    auto ptr = props.data();
    while (ptr < props_end)
      (ptr++)->is_present = false;
    return props;
  }
  props.clear();

  props.push_back(entity_properties_t(0, 0, false, bb_unset, extensibility::ext_final));  //root
  props.push_back(entity_properties_t(1, 0, false, get_bit_bound<double>(), extensibility::ext_final, false));  //::latitude
  props.push_back(entity_properties_t(1, 1, false, get_bit_bound<double>(), extensibility::ext_final, false));  //::longitude
  props.push_back(entity_properties_t(1, 2, false, get_bit_bound<double>(), extensibility::ext_final, false));  //::altitude
  props.push_back(entity_properties_t(1, 3, false, get_bit_bound<double>(), extensibility::ext_final, false));  //::speed
  props.push_back(entity_properties_t(1, 4, false, get_bit_bound<double>(), extensibility::ext_final, false));  //::track
  props.push_back(entity_properties_t(1, 5, false, get_bit_bound<double>(), extensibility::ext_final, false));  //::climb
  props.push_back(entity_properties_t(1, 6, false, get_bit_bound<int64_t>(), extensibility::ext_final, false));  //::timestamp_nanoseconds
  props.push_back(entity_properties_t(1, 7, false, get_bit_bound<bool>(), extensibility::ext_final, false));  //::valid
  props.push_back(entity_properties_t(1, 8, false, get_bit_bound<int64_t>(), extensibility::ext_final, false));  //::status
    keylist.add_key_endpoint(std::list<uint32_t>{6});

  entity_properties_t::finish(props, keylist);
  props_end = props.data() + props.size();
  initialized.store(true, std::memory_order_release);
  return props;
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

