/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: CANDBCMessage.idl
  Source: CANDBCMessage.cpp
  Cyclone DDS: v0.10.5

*****************************************************************/
#include "platform/io/can/dbc/CANDBCMessage.hpp"

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
::platform::io::can::CANBus enum_conversion<::platform::io::can::CANBus>(uint32_t in) {
  switch (in) {
    default:
    case 0:
    return ::platform::io::can::CANBus::MAIN_BUS;
    break;
    case 1:
    return ::platform::io::can::CANBus::ALT_BUS;
    break;
    case 2:
    return ::platform::io::can::CANBus::CAMERA_BUS;
    break;
  }
}

template<>
propvec &get_type_props<::platform::io::can::dbc::CANDBCSignal>() {
  static thread_local std::mutex mtx;
  static thread_local propvec props;
  static thread_local entity_properties_t *props_end = nullptr;
  static thread_local std::atomic_bool initialized {false};
  key_endpoint keylist;
  if (initialized.load(std::memory_order_relaxed)) {
    auto ptr = props.data();
    while (ptr < props_end)
      (ptr++)->is_present = false;
    return props;
  }
  std::lock_guard<std::mutex> lock(mtx);
  if (initialized.load(std::memory_order_relaxed)) {
    auto ptr = props.data();
    while (ptr < props_end)
      (ptr++)->is_present = false;
    return props;
  }
  props.clear();

  props.push_back(entity_properties_t(0, 0, false, bb_unset, extensibility::ext_final));  //root
  props.push_back(entity_properties_t(1, 0, false, get_bit_bound<uint64_t>(), extensibility::ext_final, false));  //::timestampNanoSeconds
  props.push_back(entity_properties_t(1, 1, false, bb_unset, extensibility::ext_final, false));  //::name
  props.push_back(entity_properties_t(1, 2, false, get_bit_bound<double>(), extensibility::ext_final, false));  //::value

  entity_properties_t::finish(props, keylist);
  props_end = props.data() + props.size();
  initialized.store(true, std::memory_order_release);
  return props;
}

template<>
propvec &get_type_props<::platform::io::can::dbc::CANDBCMessage>() {
  static thread_local std::mutex mtx;
  static thread_local propvec props;
  static thread_local entity_properties_t *props_end = nullptr;
  static thread_local std::atomic_bool initialized {false};
  key_endpoint keylist;
  if (initialized.load(std::memory_order_relaxed)) {
    auto ptr = props.data();
    while (ptr < props_end)
      (ptr++)->is_present = false;
    return props;
  }
  std::lock_guard<std::mutex> lock(mtx);
  if (initialized.load(std::memory_order_relaxed)) {
    auto ptr = props.data();
    while (ptr < props_end)
      (ptr++)->is_present = false;
    return props;
  }
  props.clear();

  props.push_back(entity_properties_t(0, 0, false, bb_unset, extensibility::ext_final));  //root
  props.push_back(entity_properties_t(1, 0, false, get_bit_bound<uint32_t>(), extensibility::ext_final, false));  //::address
  props.push_back(entity_properties_t(1, 1, false, bb_unset, extensibility::ext_final, false));  //::name
  props.push_back(entity_properties_t(1, 2, false, get_bit_bound<::platform::io::can::CANBus>(), extensibility::ext_final, false));  //::canBus
  props.push_back(entity_properties_t(1, 3, false, bb_unset, extensibility::ext_final, false));  //::signals
  entity_properties_t::append_struct_contents(props, get_type_props<::platform::io::can::dbc::CANDBCSignal>());  //internal contents of ::signals

  entity_properties_t::finish(props, keylist);
  props_end = props.data() + props.size();
  initialized.store(true, std::memory_order_release);
  return props;
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

