# Copyright 2023 The Apollo Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Auto generated by buildtool of apollo

STATUS = 2

SOURCE = {
    "3rd-rtklib" : {
        "path": "//third_party/rtklib",
        "depends": [
            
        ],
    },
    "perception-model-smoke-torch" : {
        "path": "//modules/perception/data/models/smoke_torch",
        "depends": [
            
        ],
    },
    "perception-model-yolo" : {
        "path": "//modules/perception/data/models/3d-r4-half_caffe",
        "depends": [
            
        ],
    },
    "perception-model-radar4d" : {
        "path": "//modules/perception/data/models/point_pillars_radar4d_torch",
        "depends": [
            
        ],
    },
    
}

BINARY = {
    "bazel-extend-tools" : {
        "path": "//tools",
        "targets": [
            
        ],
    },
    
}