# Copyright 2023 The Apollo Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Auto generated by buildtool of apollo

STATUS = 2

SOURCE = {
    "3rd-camera-library" : {
        "path": "//third_party/camera_library",
        "depends": [
            
        ],
    },
    "perception-model-mask-pillars-torch" : {
        "path": "//modules/perception/data/models/mask_pillars_torch",
        "depends": [
            
        ],
    },
    "perception-model-cnnseg128-caffe" : {
        "path": "//modules/perception/data/models/cnnseg128_caffe",
        "depends": [
            
        ],
    },
    "perception-model-point-pillars-torch" : {
        "path": "//modules/perception/data/models/point_pillars_torch",
        "depends": [
            
        ],
    },
    "perception-model-cnnseg64-caffe" : {
        "path": "//modules/perception/data/models/cnnseg64_caffe",
        "depends": [
            
        ],
    },
    "perception-model-centerpoint-paddle" : {
        "path": "//modules/perception/data/models/center_point_paddle",
        "depends": [
            
        ],
    },
    "perception-model-bevnet" : {
        "path": "//modules/perception/data/models/apollo_bevnet_onnx",
        "depends": [
            
        ],
    },
    "perception-model-cnnseg16-caffe" : {
        "path": "//modules/perception/data/models/cnnseg16_caffe",
        "depends": [
            
        ],
    },
    "perception-model-smoke-torch" : {
        "path": "//modules/perception/data/models/smoke_torch",
        "depends": [
            
        ],
    },
    "perception-model-tl-detection-caffe" : {
        "path": "//modules/perception/data/models/tl_detection_caffe",
        "depends": [
            
        ],
    },
    "perception-data-conf" : {
        "path": "//modules/perception/data/conf",
        "depends": [
            
        ],
    },
    "perception-data-flag" : {
        "path": "//modules/perception/data/flag",
        "depends": [
            
        ],
    },
    "3rd-tf2" : {
        "path": "//third_party/tf2",
        "depends": [
            "3rd-boost",
            
        ],
    },
    "perception-launch" : {
        "path": "//modules/perception/launch",
        "depends": [
            
        ],
    },
    "3rd-can-card-library" : {
        "path": "//third_party/can_card_library",
        "depends": [
            
        ],
    },
    "perception-data-params" : {
        "path": "//modules/perception/data/params",
        "depends": [
            
        ],
    },
    "calibration" : {
        "path": "//modules/calibration",
        "depends": [
            
        ],
    },
    "perception-model-vertical-caffe" : {
        "path": "//modules/perception/data/models/vertical_caffe",
        "depends": [
            
        ],
    },
    "perception-model-horizontal-caffe" : {
        "path": "//modules/perception/data/models/horizontal_caffe",
        "depends": [
            
        ],
    },
    "perception-model-radar4d" : {
        "path": "//modules/perception/data/models/point_pillars_radar4d_torch",
        "depends": [
            
        ],
    },
    "3rd-rtklib" : {
        "path": "//third_party/rtklib",
        "depends": [
            
        ],
    },
    "perception-model-quadrate-caffe" : {
        "path": "//modules/perception/data/models/quadrate_caffe",
        "depends": [
            
        ],
    },
    "perception-model-yolox3d" : {
        "path": "//modules/perception/data/models/yolox3d_onnx",
        "depends": [
            
        ],
    },
    "perception-model-yolo" : {
        "path": "//modules/perception/data/models/3d-r4-half_caffe",
        "depends": [
            
        ],
    },
    
}

BINARY = {
    "bazel-extend-tools" : {
        "path": "//tools",
        "targets": [
            
        ],
    },
    "3rd-boost" : {
        "path": "//third_party/boost",
        "targets": [
            "@boost//:boost",
            
        ],
    },
    
}